TravelProject/Models/Siniflar/Iletisim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelProject.Models.Siniflar
{
    public class Iletisim
    {
        [Key]
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
    }
}

TravelProject/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelProject.Models.Siniflar;

namespace TravelProject.Controllers
{
    public class IletisimController : Controller
    {
        // GET: Iletisim
        Context c = new Context();
        public ActionResult Index()
        {
            var result = c.Iletisims.ToList();
            return View(result);
        }


        [HttpGet]
        public PartialViewResult MesajGonder()
        {
           
            return PartialView();

        }

        [HttpPost]
        public PartialViewResult MesajGonder(Iletisim iletisim)
        {
            c.Iletisims.Add(iletisim);
            c.SaveChanges();
            return PartialView();

        }
    }
}

TravelProject/Views/Iletisim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}



<div style="text-align: left; margin: auto; width: 90%;">
    <h2>Iletisim</h2>
    <p>Gezi Blogu Ltd. Şti.</p>
    <br />
    <p> Ayazağa Mahallesi, Sarıyer – İSTANBUL</p>
    <p>Telefon : +90  535 222 22 22</p>
    <p> Fax : +90 212 222 22 22</p>
    <p>E-Mail : info@info.com</p>


    <br />
    <br />
    <p>Lütfen Bizimle İletişime Geçiniz..</p>
    <div class="col-md-8 single-main">

        @Html.Action("MesajGonder", "Iletisim")

    </div>
</div>

TravelProject/Views/Iletisim/MesajGonder.cshtml
<br /><br />
<div class="form-control">
   
    <form method="post" class="form-control">
        @*<input type="text" placeholder="Id" name="BlogId" value="@ViewBag.deger" required readonly="readonly" />*@
        <input type="text" placeholder="Adınız" name="AdSoyad" required /><br /><br />
        <input type="text" placeholder="Email" name="Email" required /><br /><br />
        <input type="text" placeholder="Konu" name="Konu" required /><br /><br />
        <textarea rows="10" cols="25" placeholder="Mesajınız" name="Mesaj" ></textarea><br /><br />
        <input type="submit"  value="GÖNDER"  /><br /><br />
    </form>
</div>